// <auto-generated />
using System;
using FonAnalizi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FonAnalizi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241021022313_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("FonAnalizi.Data.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FonAnalizi.Data.CategorySave", b =>
                {
                    b.Property<int>("SaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SaveId");

                    b.ToTable("CategoriesSaves");
                });

            modelBuilder.Entity("FonAnalizi.Data.Fon", b =>
                {
                    b.Property<int>("FonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FiveYearChange")
                        .HasColumnType("REAL");

                    b.Property<string>("FonName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FonShort")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OneDayChange")
                        .HasColumnType("REAL");

                    b.Property<double?>("OneMonthChange")
                        .HasColumnType("REAL");

                    b.Property<double?>("OneWeekChange")
                        .HasColumnType("REAL");

                    b.Property<double?>("OneYearChange")
                        .HasColumnType("REAL");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double?>("SixMonthChange")
                        .HasColumnType("REAL");

                    b.Property<double?>("ThreeMonthChange")
                        .HasColumnType("REAL");

                    b.Property<double?>("ThreeYearChange")
                        .HasColumnType("REAL");

                    b.HasKey("FonId");

                    b.ToTable("Fons");
                });
#pragma warning restore 612, 618
        }
    }
}
